apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  selector:
    name: currency
  type: NodePort
  ports:
  - port: 4001
    targetPort: 4001
    nodePort: 30038
    protocol: TCP